name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest # Specifies a Windows-based runner

    steps:
    - uses: actions/checkout@v4 # Checks out the repository code

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Specifies the .NET SDK version to use
      
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Build
      run: npm run build:abi127  # Builds the project in Release configuration
